# Generated by Django 5.2.1 on 2025-06-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_product_comments_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='в наличии'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сколько продано'),
        ),
    ]
