# Generated by Django 5.2.1 on 2025-06-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_category_level_remove_product_count_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_count',
            field=models.PositiveIntegerField(null=True, verbose_name='в наличии'),
        ),
    ]
