# Generated by Django 5.2.1 on 2025-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/about-img.jpg', upload_to='product_images/', verbose_name='Фото'),
        ),
    ]
