# Generated by Django 5.2.1 on 2025-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
