# Generated by Django 5.2.1 on 2025-06-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_faq_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('order_payment', 'Оплата заказа'), ('balance_replenishment', 'Пополнение баланса')], default='order_payment', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='blog.order'),
        ),
    ]
