# Generated by Django 5.2.1 on 2025-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_payment_payment_type_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
