# Generated by Django 5.2.1 on 2025-07-10 10:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_payment_card_expiry_alter_payment_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default=blog.models.get_order_expiration),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(default=blog.models.get_payment_expiration),
        ),
    ]
