# Generated by Django 5.2.1 on 2025-07-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_order_expires_at_payment_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
